[package]
name = "wide"
description = "A crate to help you go wide."
version = "1.5.0"
authors = ["Lokathor <zefria@gmail.com>"]
autotests = false
repository = "https://github.com/Lokathor/wide"
readme = "README.md"
keywords = ["simd", "wide", "lokathor"]
categories = ["data-structures", "hardware-support"]
edition = "2024"
license = "Zlib OR Apache-2.0 OR MIT"

# When updating, also update CI workflows and the badge in the README.
rust-version = "1.89"

[features]
default = ["all-types", "std"]

# There is a feature flag for each SIMD type.
f32x4 = []
f32x8 = []
f32x16 = []
f64x2 = []
f64x4 = []
f64x8 = []
i8x16 = []
i8x32 = []
i16x8 = []
i16x16 = []
i16x32 = []
i32x4 = []
i32x8 = []
i32x16 = []
i64x2 = []
i64x4 = []
i64x8 = []
u8x16 = []
u8x32 = []
u16x8 = []
u16x16 = []
u16x32 = []
u32x4 = []
u32x8 = []
u32x16 = []
u64x2 = []
u64x4 = []
u64x8 = []

# Enables all SIMD types (enabled by default).
all-types = [
    "f32x4",
    "f32x8",
    "f32x16",
    "f64x2",
    "f64x4",
    "f64x8",
    "i8x16",
    "i8x32",
    "i16x8",
    "i16x16",
    "i16x32",
    "i32x4",
    "i32x8",
    "i32x16",
    "i64x2",
    "i64x4",
    "i64x8",
    "u8x16",
    "u8x32",
    "u16x8",
    "u16x16",
    "u16x32",
    "u32x4",
    "u32x8",
    "u32x16",
    "u64x2",
    "u64x4",
    "u64x8",
]

# Activate `std` within the crate. Currently this gives a much faster `sqrt`
# impl when an explicit hardware sqrt isn't available.
std = []
serde = ["dep:serde_core"]

[target.'cfg(target_arch = "x86")'.dependencies]
safe_arch = { version = "1.0.0", features = ["bytemuck"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
safe_arch = { version = "1.0.0", features = ["bytemuck"] }

[dependencies]
serde_core = { version = "1", default-features = false, optional = true }
bytemuck = "1.24.0"

[dev-dependencies]
bincode = { version = "1.3.3" }
criterion = { version = "0.7.0", default-features = false }

[[test]]
name = "tests"
path = "tests/main.rs"

[[bench]]
name = "fma_benchmarks"
harness = false

[[bench]]
name = "math_benchmarks"
harness = false
